/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 1, 2 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 2.0405249958287754, 9.140239577188572, 595.2282123635674 };
const float ei_classifier_anom_mean[3] = { 27.043349717279224, 72.66360218994453, 384.5320163789917 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[3] = {
	{ ( float[3] ) { -0.1606893539428711, 0.502758800983429, -0.4641023278236389 }, 1.8873310865347428 },
	{ ( float[3] ) { -1.741740107536316, -2.3177762031555176, -0.1703166514635086 }, 1.6726565108806133 },
	{ ( float[3] ) { 1.0196751356124878, -0.5385474562644958, 1.4090174436569214 }, 3.1464383795098523 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
